"""Routes for the main Reports dashboard."""

import json
import os
import sys
from functools import wraps

from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    send_file,
    session,
    url_for,
)

# Add the main src directory to the path to import from mockCMMS
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "..", "..", "..", "src"))
from apps.reports.src import models as report_models  # noqa: E402
from apps.reports.src.services import data_aggregator as da_service  # noqa: E402
from apps.reports.src.services import report_generator as rg_service  # noqa: E402
from src.services.db_utils import Team, db  # noqa: E402

from .shift_report import shift_bp  # noqa: E402
from .weekend_report import weekend_bp  # noqa: E402

reports_bp = Blueprint(
    "reports",
    __name__,
    url_prefix="/reports",
    template_folder="../templates",
    static_folder="../static",
    static_url_path="/static",
)

# Register sub-blueprints
reports_bp.register_blueprint(weekend_bp)
reports_bp.register_blueprint(shift_bp)


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        print(f"DEBUG: login_required check. Session keys: {list(session.keys())}")
        if "user_id" not in session:
            flash("Login required to access this page.", "warning")
            return redirect("/login")
        return f(*args, **kwargs)

    return decorated_function


@reports_bp.route("/")
@login_required
def reports():
    try:
        # Import User from db_utils where it's defined (not src.models)
        from src.services.db_utils import User

        # Create reports table if it doesn't exist using checkfirst=True
        # This safely handles the case where table already exists
        try:
            reports_engine = db.get_engine(bind="reports")
            report_models.Report.__table__.create(reports_engine, checkfirst=True)
        except Exception as table_err:
            current_app.logger.debug(f"Table check skipped: {table_err}")

        # Fetch only reports generated by current logic (or all)
        reports_list = report_models.Report.query.order_by(
            report_models.Report.generated_on.desc()
        ).all()

        reports_data = []
        for r in reports_list:
            r_dict = r.to_dict()
            # Resolve generated_by ID to Name if possible
            r_dict["generated_by_name"] = "System"
            if r.generated_by:
                try:
                    user = User.query.filter_by(id=r.generated_by).first()
                    if user:
                        r_dict["generated_by_name"] = user.username
                except Exception:
                    r_dict["generated_by_name"] = "Unknown"
            reports_data.append(r_dict)

        return render_template("reports.html", reports=reports_data)
    except Exception as e:
        current_app.logger.error(f"Error loading reports: {e}")
        # Fallback if table creation fails or other DB issues
        return render_template("reports.html", reports=[])


@reports_bp.route("/generate", methods=["GET", "POST"])
@login_required
def generate_report():
    if request.method == "POST":
        # Ensure table exists using checkfirst=True to avoid errors
        try:
            reports_engine = db.get_engine(bind="reports")
            report_models.Report.__table__.create(reports_engine, checkfirst=True)
        except Exception as e:
            current_app.logger.debug(f"Table check skipped: {e}")

        title = request.form.get("title")
        report_type = request.form.get("report_type")

        # Validate required fields FIRST
        if not title:
            flash("Report Title is required.", "danger")
            return render_template("report_generate.html")

        if not report_type:
            flash("Report Type is required.", "danger")
            return render_template("report_generate.html")

        # New Feature: Handover Inputs (Process as list based on newlines)
        handover_from_raw = request.form.get("handover_from_previous", "")
        handover_to_raw = request.form.get("handover_to_next", "")

        # Split by newline and filter empty
        handover_from_previous = [
            line.strip() for line in handover_from_raw.splitlines() if line.strip()
        ]
        handover_to_next = [
            line.strip() for line in handover_to_raw.splitlines() if line.strip()
        ]

        parameters = {}
        data = {}

        if report_type == "shift_report":
            date_str = request.form.get("shift_date")
            shift_name = request.form.get("shift_name")

            # Validation: Ensure date is provided
            if not date_str:
                flash("Shift Date is required.", "danger")
                return render_template("report_generate.html")

            parameters = {"date": date_str, "shift": shift_name}
            aggregator = da_service.DataAggregator()
            data = aggregator.get_aggregated_shift_data(date_str, shift_name)

            # Inject user-provided Handover notes into the data
            if "shift_info" in data:
                data["shift_info"]["handover_from_previous"] = handover_from_previous
                data["shift_info"]["handover_to_next"] = handover_to_next
            else:
                data["handover_from_previous"] = handover_from_previous
                data["handover_to_next"] = handover_to_next

        elif report_type == "weekend_report":
            weekend_date = request.form.get("weekend_date")

            # Validation
            if not weekend_date:
                flash("Weekend Date is required.", "danger")
                return render_template("report_generate.html")

            parameters = {"weekend_date": weekend_date}
            aggregator = da_service.DataAggregator()
            data = aggregator.get_aggregated_weekend_data(weekend_date)

            # Append handover notes if relevant for weekend report too
            # Use 'handover_to_next' as general instructions
            data["handover_instructions"] = handover_to_next

        # STRICT DB ONLY: No file generation for the main report entry
        file_path = None

        # Create DB entry with DATA stored directly
        new_report = report_models.Report(
            title=title,
            report_type=report_type,
            parameters=parameters,
            data=data,  # Store content in DB
            file_path=file_path,
            generated_by=session.get("user_id"),
        )
        db.session.add(new_report)
        db.session.commit()

        flash("Report generated successfully!", "success")
        return redirect(url_for("reports.reports"))

    return render_template("report_generate.html")


@reports_bp.route("/<int:report_id>")
@login_required
def report_detail(report_id):
    from src.services.db_utils import Asset, User

    report = report_models.Report.query.get_or_404(report_id)

    # Resolve generated_by ID to name
    report.generated_by_name = "System"
    if report.generated_by:
        try:
            user = User.query.filter_by(id=report.generated_by).first()
            if user:
                report.generated_by_name = user.username
        except Exception:
            report.generated_by_name = "Unknown"

    # Load report data from DB
    data = report.data or {}

    # Fallback for old reports or if data is missing in DB but file exists
    # (migration path)
    if (
        not data
        and report.file_path
        and report.file_path.endswith(".json")
        and os.path.exists(report.file_path)
    ):
        try:
            with open(report.file_path, "r") as f:
                data = json.load(f)
        except Exception:
            pass

    if not data:
        flash("Report data not available.", "warning")

    # Select template based on report type
    template_name = "report_detail.html"  # Default
    if report.report_type == "shift_report":
        template_name = "shift_report_detail.html"
    elif report.report_type == "weekend_report":
        template_name = "weekend_report_detail.html"

    # Fetch teams for dropdowns
    # Get distinct team names from users
    teams = []
    try:
        # Query Team table directly for team names
        teams_query = db.session.query(Team.name).order_by(Team.name).all()
        teams = [t[0] for t in teams_query if t[0]]
    except Exception as e:
        current_app.logger.warning(f"Failed to fetch teams: {e}")
        teams = []  # Empty list, no fallback teams

    # Fetch Assets for dropdowns
    assets = []
    try:
        assets_query = (
            Asset.query.with_entities(Asset.asset_code).order_by(Asset.asset_code).all()
        )
        assets = [a[0] for a in assets_query]  # with_entities returns tuples
    except Exception as e:
        current_app.logger.warning(f"Failed to fetch assets: {e}")

    # Load config for metadata totals (equipment, technology)
    config_path = os.path.join(os.path.dirname(__file__), "..", "config", "config.json")
    metadata_config = {"equipment_1_total": 10, "equipment_2_total": 15}  # Defaults
    try:
        if os.path.exists(config_path):
            with open(config_path, "r") as f:
                config = json.load(f)
                metadata_config = config.get("metadata_totals", metadata_config)
    except Exception as e:
        current_app.logger.warning(f"Failed to load config: {e}")

    # Get technician count for attendance total
    technician_count = 0
    try:
        # Count users in the same team as the report's team
        # Since this is a historical report, we should probably prefer a stored
        # total if available
        # But if not, we default to current DB count.

        # Check if stored in data first (added via new logic)
        if data.get("attendance_total"):
            technician_count = int(data.get("attendance_total"))
        else:
            # Fallback: Count users in the same team as the report's team
            report_team = data.get("team_name", "")  # Top level name
            if not report_team and "shift_info" in data:
                report_team = data["shift_info"].get("team_name", "")

            if report_team:
                team_obj = Team.query.filter_by(name=report_team).first()
                if team_obj:
                    technician_count = User.query.filter_by(team=team_obj).count()

            # If still low/zero and we have dummy data "Team A" scenario with only
            # 4 seed users
            # The user might be expecting 18?
            # We can override if attendance > count (impossible normally)
            attendance_val = int(data.get("attendance", 0))
            if attendance_val > technician_count:
                # Assume missing data or simulation, fallback to attendance value
                # or reasonable total?
                # No, let's just use attendance value matching if it's dummy data
                # Actually, if technician_count is 4, it's 4. User asked "Why 4?".
                # Answer: Because there are 4 technicians in DB.
                # But sticking to "defaults":
                pass

    except Exception as e:
        current_app.logger.warning(f"Failed to count technicians: {e}")

    return render_template(
        template_name,
        report=report,
        data=data,
        teams=teams,
        assets=assets,
        vigel_total=metadata_config.get("vigel_total", 10),
        mds_total=metadata_config.get("mds_total", 15),
        technician_count=technician_count,
    )


@reports_bp.route("/<int:report_id>/update", methods=["POST"])
@login_required
def update_report_data(report_id):
    """Update a specific section of the report data.

    Expects JSON payload with:
    - section: 'header', 'metadata', 'breakdown', etc.
    - index: index of item in list (if applicable)
    - action: 'edit', 'add', 'delete'
    - ... specific fields ...
    """
    report = report_models.Report.query.get_or_404(report_id)
    payload = request.get_json()

    if not payload:
        return {"success": False, "error": "No data provided"}, 400

    current_data = report.data or {}
    section = payload.get("section")
    action = payload.get("action")
    index = payload.get("index")

    # Helper to save
    def save():
        report.data = current_data
        # Force strict update
        from sqlalchemy.orm.attributes import flag_modified

        flag_modified(report, "data")
        db.session.commit()

    try:
        # --- HEADER ---
        if section == "header":
            if "shift_info" not in current_data:
                current_data["shift_info"] = {}
            current_data["shift_info"]["date"] = payload.get("date")
            current_data["shift_info"]["shift"] = payload.get("shift")

            # Update both top-level and shift_info team_name to ensure UI reflects it
            new_team = payload.get("team_name")
            current_data["team_name"] = new_team
            current_data["shift_info"]["team_name"] = new_team

            current_data["team_color"] = payload.get("team_color")
            save()
            return {"success": True}

        # --- METADATA ---
        if section == "metadata":
            key = payload.get("key")
            value = payload.get("value")
            if key:
                current_data[key] = value
                save()
                return {"success": True}

        # --- HANDOVER ---
        if section in ["handover_from", "handover_to", "handover"]:
            # Map section name to data key
            # data_key = "handover_instructions"  # default for weekend
            if section == "handover_from":
                if "shift_info" not in current_data:
                    current_data["shift_info"] = {}
                # This refers to shift_info['handover_from_previous']
                # The structure in shift report:
                # current_data['shift_info']['handover_from_previous'] ->
                # list of strings or objects?
                # DataAggregator returns list of strings usually.
                # Let's standardize on objects: { asset, title, description }
                # or simple string
                target_list = current_data.get("shift_info", {}).get(
                    "handover_from_previous", []
                )
                # If target list is missing in shift_info, init it
                if "handover_from_previous" not in current_data.get("shift_info", {}):
                    if "shift_info" not in current_data:
                        current_data["shift_info"] = {}
                    current_data["shift_info"]["handover_from_previous"] = []
                    target_list = current_data["shift_info"]["handover_from_previous"]
            elif section == "handover_to":
                if "shift_info" not in current_data:
                    current_data["shift_info"] = {}
                target_list = current_data.get("shift_info", {}).get(
                    "handover_to_next", []
                )
                if "handover_to_next" not in current_data.get("shift_info", {}):
                    current_data["shift_info"]["handover_to_next"] = []
                    target_list = current_data["shift_info"]["handover_to_next"]
            else:
                # Weekend report / general
                target_list = current_data.get("handover_instructions", [])
                if "handover_instructions" not in current_data:
                    current_data["handover_instructions"] = []
                    target_list = current_data["handover_instructions"]

            # Construct Item
            item = payload.get("description")  # fallback
            # If we want detailed object:
            if payload.get("asset") or payload.get("title"):
                item = {
                    "asset": payload.get("asset"),
                    "title": payload.get("title"),
                    "description": payload.get("description"),
                }

            # ACTION
            if action == "edit" and index is not None:
                index = int(index)
                if 0 <= index < len(target_list):
                    # For shift report handovers, we need to update the list in place
                    # But we only have a reference 'target_list'.
                    # Reference modification:
                    target_list[index] = item
            elif action == "add":
                target_list.append(item)
            elif action == "delete" and index is not None:
                index = int(index)
                if 0 <= index < len(target_list):
                    target_list.pop(index)

            save()
            return {"success": True}

        # --- BREAKDOWNS ---
        if section == "breakdown":
            target_list = current_data.get("breakdowns", [])
            item = {
                "equipment_line": payload.get(
                    "asset"
                ),  # Mapping asset -> equipment_line for consistency
                "timestamp": payload.get("timestamp"),
                "duration": payload.get("duration"),
                "description": payload.get("description"),
                "root_cause": payload.get("root_cause"),
                "resolution_notes": payload.get("resolution_notes"),
            }

            if action == "edit" and index is not None:
                target_list[int(index)] = item
            elif action == "add":
                target_list.append(item)
            elif action == "delete" and index is not None:
                target_list.pop(int(index))

            current_data["breakdowns"] = target_list
            save()
            return {"success": True}

        # --- ACTIVITIES (Generic Add / Specific Edit) ---
        # Handle 'activities' (Add), 'flux_tickets' (Edit/Del),
        # 'engineering_support' (Edit/Del)
        if section in ["activities", "flux_tickets", "engineering_support"]:
            # Determine target list based on section or type (for Add)
            target_key = "break_activities"  # Default
            target_list = []

            # If explicit section (Edit/Delete)
            if section == "flux_tickets":
                target_key = "break_activities"
            elif section == "engineering_support":
                target_key = "engineering_support"
            elif section == "activities" and action == "add":
                # For ADD via generic modal, check type from payload
                act_type = payload.get("type", "flux_ticket")
                if act_type == "flux_ticket":
                    target_key = "break_activities"
                else:
                    target_key = "engineering_support"

            # Fetch current list
            target_list = current_data.get(target_key, [])
            if not target_list and target_key in current_data:
                # target_list = current_data[target_key]
                # Use retrieval by key directly if get returned empty list but key
                # exists
                target_list = current_data[target_key]

            # Construct Item
            item = {
                "asset": payload.get("asset"),
                "title": payload.get("title"),  # For Eng Support
                "description": payload.get("description"),
                "type": payload.get("type"),  # For FLUX
                "mo_id": payload.get("mo_id"),  # For FLUX
                "status": payload.get("status"),  # For FLUX
            }

            if action == "edit" and index is not None:
                # For FLUX tickets, we need to be careful if list is mixed?
                # No, break_activities is list of all Flux tickets usually.
                # But engineering_support is separate key.
                if 0 <= int(index) < len(target_list):
                    target_list[int(index)] = item
            elif action == "add":
                target_list.append(item)
            elif action == "delete" and index is not None:
                if 0 <= int(index) < len(target_list):
                    target_list.pop(int(index))

            current_data[target_key] = target_list
            save()
            return {"success": True}

        # --- TASKS (PMs / MOs) ---
        if section in ["pms", "mos", "additional"]:
            key_map = {
                "pms": "pms",
                "mos": "mos",
                "additional": "additional_tickets",  # Check exact key in weekend data
            }
            key = key_map.get(section, section)
            target_list = current_data.get(key, [])

            item = {
                "asset": payload.get("asset"),
                "description": payload.get("description"),
                "status": payload.get("status"),
            }
            if payload.get("id"):
                item["id"] = payload.get("id")

            if action == "edit" and index is not None:
                target_list[int(index)] = item
            elif action == "add":
                target_list.append(item)
            elif action == "delete" and index is not None:
                target_list.pop(int(index))

            current_data[key] = target_list
            save()
            return {"success": True}

        # Fallback
        return {"success": False, "error": "Unknown section or action"}, 400

    except Exception as e:
        current_app.logger.error(f"Update failed: {e}")
        return {"success": False, "error": str(e)}, 500


@reports_bp.route("/<int:report_id>/download")
@login_required
def download_report(report_id):
    report = report_models.Report.query.get_or_404(report_id)
    if report.file_path and os.path.exists(report.file_path):
        return send_file(report.file_path, as_attachment=True)
    else:
        # Generate on the fly if missing?
        flash("File not found. Try Export options.", "danger")
        return redirect(url_for("reports.report_detail", report_id=report_id))


@reports_bp.route("/<int:report_id>/delete", methods=["POST"])
@login_required
def delete_report(report_id):
    report = report_models.Report.query.get_or_404(report_id)
    try:
        # Optional: Delete file
        if report.file_path and os.path.exists(report.file_path):
            os.remove(report.file_path)

        db.session.delete(report)
        db.session.commit()
        flash("Report deleted.", "success")
    except Exception as e:
        db.session.rollback()
        flash(f"Error deleting report: {e}", "danger")

    return redirect(url_for("reports.reports"))


@reports_bp.route("/<int:report_id>/export/<fmt>")
@login_required
def export_report(report_id, fmt):
    """On-the-fly export of a report to a different format.

    Regenerates the report content using the stored DB data.
    """
    report = report_models.Report.query.get_or_404(report_id)

    # Get valye from DB
    data = report.data

    # Fallback to file if DB empty
    if (
        not data
        and report.file_path
        and report.file_path.endswith(".json")
        and os.path.exists(report.file_path)
    ):
        with open(report.file_path, "r") as f:
            data = json.load(f)

    if not data:
        flash("Source data for this report is missing. Cannot export.", "danger")
        return redirect(url_for("reports.report_detail", report_id=report_id))

    # Generate the requested format
    generator = rg_service.ReportGenerator()

    export_title = f"{report.title}_export_{fmt}"

    try:
        target_fmt = fmt
        # if fmt == "txt":
        #    target_fmt = "markdown"

        # Handle parameters - could be dict (from JSON column) or string
        params = report.parameters
        if isinstance(params, str):
            params = json.loads(params)
        elif params is None:
            params = {}

        new_file_path = generator.generate_report(
            report.report_type,
            export_title,
            params,
            target_fmt,
            session.get("user_id"),
            data=data,
        )

        if new_file_path and os.path.exists(new_file_path):
            return send_file(
                new_file_path,
                as_attachment=True,
                download_name=os.path.basename(new_file_path),
            )
        else:
            flash("Export file could not be created.", "danger")

    except Exception as e:
        current_app.logger.error(f"Export failed: {e}")
        flash(f"Export failed: {e}", "danger")

    return redirect(url_for("reports.report_detail", report_id=report_id))
