from setuptools import setup, find_packages

setup(
    name='planning',
    version='0.1.0',
    packages=find_packages(where='src'),
    package_dir={'': 'src'},
    include_package_data=True,
    install_requires=[
        'requests',
        'blinker==1.9.0',
        'click==8.2.1',
        'colorama==0.4.6',
        'Deprecated==1.2.18',
        'Flask==3.1.1',
        'Flask-Limiter==3.8.0',
        'Flask-WTF==1.2.1',
        'iniconfig==2.1.0',
        'itsdangerous==2.2.0',
        'Jinja2==3.1.6',
        'limits==5.5.0',
        'markdown-it-py==4.0.0',
        'MarkupSafe==3.0.2',
        'mdurl==0.1.2',
        'numpy==2.2.6',
        'ordered-set==4.1.0',
        'packaging==25.0',
        'pandas==2.3.0',
        'pandas-stubs==2.2.3.250527',
        'pluggy==1.6.0',
        'Pygments==2.19.2',
        'pytest==8.4.1',
        'python-dateutil==2.9.0.post0',
        'python-dotenv==1.0.1',
        'pytz==2025.2',
        'pyxlsb==1.0.10',
        'rich==13.9.4',
        'six==1.17.0',
        'types-pytz==2025.2.0.20250809',
        'typing_extensions==4.14.1',
        'tzdata==2025.2',
        'Werkzeug==3.1.4',
        'wrapt==1.17.3',
        'WTForms==3.2.1',
    ],
    description='Planning application as a Flask Blueprint',
    author='Your Name',
    author_email='your.email@example.com',
    url='http://your-project-url.com',
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.9',
)
