#!/usr/bin/env python3
"""Artifact Cleanup Script.

Removes generated files and directories produced by testing, linting,
and formatting tools to keep the repository clean between runs.

Can be run standalone or imported and called from other scripts.

Usage:
    python scripts/cleanup.py              # Clean test artifacts + coverage (default)
    python scripts/cleanup.py --all        # Clean everything including caches
    python scripts/cleanup.py --coverage   # Only coverage reports (.coverage, htmlcov/)
    python scripts/cleanup.py --tests      # Only test output (playwright-report/, jest
                                           # coverage/)
    python scripts/cleanup.py --caches     # Only tool caches (pycache, mypy, ruff,
                                           # eslint)
    python scripts/cleanup.py --dry-run    # Show what would be deleted without deleting
"""

import argparse
import sys
from pathlib import Path
from typing import List, Tuple

ROOT = Path(__file__).parent.parent

# Directories/files that should NEVER be cleaned regardless of flags
PROTECTED = {".venv", "venv", "node_modules", ".git", "instance", "test_data"}

# ---------------------------------------------------------------------------
# Artifact groups
# ---------------------------------------------------------------------------

# Coverage reports and data files generated by pytest-cov and Jest
COVERAGE_ARTIFACTS: List[str] = [
    "htmlcov",  # pytest HTML coverage report (--cov-report=html)
    ".coverage",  # pytest coverage data file
    "coverage.xml",  # pytest XML coverage (--cov-report=xml)
    "coverage",  # Jest coverage directory (--coverage)
    "lcov.info",  # LCOV coverage format
]

# Glob patterns for scattered coverage files (e.g. parallel pytest runs)
COVERAGE_GLOB_PATTERNS: List[str] = [
    ".coverage.*",  # Parallel coverage data: .coverage.hostname.pid
]

# Test output: reports, traces, screenshots on failure, and duplicate-code output
TEST_OUTPUT_ARTIFACTS: List[str] = [
    "playwright-report",  # Playwright HTML report
    "test-results",  # Playwright traces/videos/screenshots on failure
    "blob-report",  # Playwright blob reporter output
    ".playwright-artifacts",  # Playwright internal artifacts
    "jscpd-report",  # JSCPD duplicate code report
    ".jscpd",  # JSCPD internal cache
]

# Glob patterns for scattered test output files
TEST_OUTPUT_GLOB_PATTERNS: List[str] = [
    "jest_output.txt",
    "jest_*.txt",
]

# Tool caches that speed up subsequent runs but pollute the repo visually.
# These are optional (--caches / --all) since cleaning them slows next run.
CACHE_ARTIFACTS: List[str] = [
    ".pytest_cache",  # Pytest test cache
    ".mypy_cache",  # Mypy type-check cache
    ".ruff_cache",  # Ruff lint cache
    ".bandit_cache",  # Bandit security scan cache
]

# Glob patterns for scattered cache files
CACHE_GLOB_PATTERNS: List[str] = [
    "**/.eslintcache",  # ESLint cache (created next to the project root or in subdirs)
    "**/__pycache__",  # Python bytecode cache (scattered everywhere)
    "**/*.pyc",  # Compiled Python bytecode files
    "**/*.pyo",  # Optimised Python bytecode files
]


def _is_protected(path: Path) -> bool:
    """Return True if any part of the path is in the protected set."""
    return any(part in PROTECTED for part in path.parts)


def _remove(path: Path, dry_run: bool) -> Tuple[bool, str]:
    """Delete a file or directory tree.

    Args:
        path: Path to remove.
        dry_run: If True, only report what would be removed.

    Returns:
        Tuple of (success, message).
    """
    if not path.exists():
        return False, ""

    kind = "dir" if path.is_dir() else "file"
    label = f"  🗑  [{kind}] {path.relative_to(ROOT)}"

    if dry_run:
        return True, f"[DRY-RUN] {label}"

    try:
        if path.is_dir():
            import shutil

            shutil.rmtree(path)
        else:
            path.unlink()
        return True, label
    except PermissionError as exc:
        return False, f"  ⚠  Could not remove {path}: {exc}"
    except OSError as exc:
        return False, f"  ⚠  Could not remove {path}: {exc}"


def _clean_top_level(names: List[str], dry_run: bool) -> int:
    """Remove top-level artifacts by exact name relative to ROOT.

    Args:
        names: List of names to look for directly under ROOT.
        dry_run: If True, only report.

    Returns:
        Number of items removed (or would-be removed).
    """
    count = 0
    for name in names:
        path = ROOT / name
        ok, msg = _remove(path, dry_run)
        if msg:
            print(msg)
        if ok:
            count += 1
    return count


def _clean_glob(patterns: List[str], dry_run: bool) -> int:
    """Remove files/dirs matching glob patterns anywhere under ROOT.

    Skips protected directories and .venv paths automatically.

    Args:
        patterns: List of glob patterns relative to ROOT.
        dry_run: If True, only report.

    Returns:
        Number of items removed (or would-be removed).
    """
    count = 0
    seen: set = set()

    for pattern in patterns:
        for match in sorted(ROOT.glob(pattern)):
            # Avoid double-processing nested matches
            if match in seen:
                continue
            seen.add(match)

            if _is_protected(match.relative_to(ROOT)):
                continue

            ok, msg = _remove(match, dry_run)
            if msg:
                print(msg)
            if ok:
                count += 1

    return count


def clean_coverage(dry_run: bool = False) -> int:
    """Remove coverage reports and data files.

    Args:
        dry_run: If True, only report what would be removed.

    Returns:
        Total number of items cleaned.
    """
    total = 0
    total += _clean_top_level(COVERAGE_ARTIFACTS, dry_run)
    total += _clean_glob(COVERAGE_GLOB_PATTERNS, dry_run)
    return total


def clean_test_output(dry_run: bool = False) -> int:
    """Remove test runner output (playwright-report, jest output, etc.).

    Args:
        dry_run: If True, only report what would be removed.

    Returns:
        Total number of items cleaned.
    """
    total = 0
    total += _clean_top_level(TEST_OUTPUT_ARTIFACTS, dry_run)
    total += _clean_glob(TEST_OUTPUT_GLOB_PATTERNS, dry_run)
    return total


def clean_caches(dry_run: bool = False) -> int:
    """Remove tool caches (__pycache__, .mypy_cache, .ruff_cache, etc.).

    Note: Removing these makes the next tool run slightly slower because
    caches must be rebuilt.

    Args:
        dry_run: If True, only report what would be removed.

    Returns:
        Total number of items cleaned.
    """
    total = 0
    total += _clean_top_level(CACHE_ARTIFACTS, dry_run)
    total += _clean_glob(CACHE_GLOB_PATTERNS, dry_run)
    return total


def clean_default(dry_run: bool = False) -> int:
    """Remove test artifacts and coverage reports (default behaviour).

    Keeps tool caches (.pytest_cache, .mypy_cache, etc.) intact so
    subsequent runs stay fast.

    Args:
        dry_run: If True, only report what would be removed.

    Returns:
        Total number of items cleaned.
    """
    return clean_coverage(dry_run) + clean_test_output(dry_run)


def clean_all(dry_run: bool = False) -> int:
    """Remove everything: coverage, test output, AND tool caches.

    Args:
        dry_run: If True, only report what would be removed.

    Returns:
        Total number of items cleaned.
    """
    return clean_default(dry_run) + clean_caches(dry_run)


def main() -> int:
    """Entry point for standalone execution."""
    parser = argparse.ArgumentParser(
        description=(
            "Remove generated artifacts from testing, linting, and formatting tools."
        )
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--all",
        action="store_true",
        help="Clean everything including tool caches (__pycache__, .mypy_cache, etc.)",
    )
    group.add_argument(
        "--coverage",
        action="store_true",
        help="Only remove coverage reports and data files",
    )
    group.add_argument(
        "--tests",
        action="store_true",
        help="Only remove test runner output (playwright-report, jest coverage, etc.)",
    )
    group.add_argument(
        "--caches",
        action="store_true",
        help="Only remove tool caches (__pycache__, .mypy_cache, .ruff_cache, etc.)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be deleted without actually deleting anything",
    )

    args = parser.parse_args()

    print("\n" + "=" * 60)
    mode = "[DRY-RUN] " if args.dry_run else ""
    print(f"{mode}🧹 ARTIFACT CLEANUP")
    print("=" * 60)

    if args.all:
        label, count = "all artifacts (including caches)", clean_all(args.dry_run)
    elif args.coverage:
        label, count = "coverage artifacts", clean_coverage(args.dry_run)
    elif args.tests:
        label, count = "test output artifacts", clean_test_output(args.dry_run)
    elif args.caches:
        label, count = "tool caches", clean_caches(args.dry_run)
    else:
        label, count = "test artifacts + coverage", clean_default(args.dry_run)

    print()
    if count:
        verb = "Would remove" if args.dry_run else "Removed"
        print(f"✅ {verb} {count} item(s) from {label}.")
    else:
        print(f"✨ Nothing to clean in {label}.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
