name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Format Release PR
        if: ${{ steps.release.outputs.pr }}
        run: |
          npm ci
          npx prettier --write CHANGELOG.md README.md
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md README.md
          git commit -m "chore: format documentation for release" || exit 0
          git push origin ${{ steps.release.outputs.pr.branch }}
